### ISSUE TITLE
child views (how to handle)

### ISSUE THREAD

**Issue by ernani** [webjars/sample-play2#9]
if my index contains child views and I use them with @otherview it won't resolve

This @otherview (otherview.scala.html) does load the webjars (part of <head> tags)

How can this be resolved?
Thanks a lot in advance!

**Comment by jamesward** [comment]
If you are using template injection (Play 2.6) you can inject `org.webjars.play.WebJarsUtil` into any template.  Does that help?

**Comment by ernani** [comment]
I guess I've made a confusion, I've missed the @Inject tags in the controller class, that was the issue. Thanks a lot for such awesome component! Closing the issue!
